### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by bgagan911** [GabMus/gestureManager#2]
I'm getting this error message. Running Lubuntu with LXDE
```
root# ./main.py 
Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    import gi
  File "/opt/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
```

**Comment by adrfantini** [comment]
@bgagan911 That looks like a python2/3 issue, try to run it with python3.

However, on Arch with the latest git from AUR it still fails:
```
python3 /usr/share/gesture-manager/main.py
Traceback (most recent call last):
  File "/usr/share/gesture-manager/main.py", line 3, in <module>
    gi.require_version("Gtk", "3.0")
AttributeError: module 'gi' has no attribute 'require_version'
```

**Comment by marine1988** [comment]
I have the same problem?

**Comment by jacob-ammon** [comment]
I have the same problem. I know i am in python 3.6.3, and when I type `sudo python main.py` its gives me this error:
 "Traceback (most recent call last):
  File "main.py", line 103, in <module>
    update_daemon_status()
  File "main.py", line 69, in update_daemon_status
    status=daemonHelper.get_daemon_running()
  File "/home/janderson/gestureManager/daemonHelper.py", line 16, in get_daemon_running
    running_s=status[2].split()
IndexError: list index out of range
"
I would love to know what is going on!
